spring:
  application:
    name: stock-service

server:
  port: 8301
  

eureka:
  client:
    resgisterWithEureka: true
    featchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
  instance:
    hostname: localhost
    
    